server:
  port: 8080

spring:
  application:
    name: ewm-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm}
    username: ${SPRING_DATASOURCE_USERNAME:ewm_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

stats-server:
  url: ${STATS_SERVER_URL:http://localhost:9090}

logging:
  level:
    ru.practicum: DEBUG