CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    initiator_id BIGINT NOT NULL REFERENCES users(id),
    location_id BIGINT NOT NULL REFERENCES locations(id),
    paid BOOLEAN NOT NULL,
    participant_limit INTEGER,
    request_moderation BOOLEAN,
    state VARCHAR(255) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    published_on TIMESTAMP,
    title VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT NOT NULL REFERENCES compilations(id),
    event_id BIGINT NOT NULL REFERENCES events(id),
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on TIMESTAMP NOT NULL,
    event_id BIGINT NOT NULL REFERENCES events(id),
    requester_id BIGINT NOT NULL REFERENCES users(id),
    status VARCHAR(255) NOT NULL
);

DELETE FROM participation_requests;
DELETE FROM compilations_events;
DELETE FROM compilations;
DELETE FROM events;
DELETE FROM locations;
DELETE FROM categories;
DELETE FROM users;

INSERT INTO users (name, email) VALUES ('Test User', 'test@test.com');
INSERT INTO categories (name) VALUES ('Test Category');
INSERT INTO locations (lat, lon) VALUES (55.0, 37.0);

INSERT INTO events (
    annotation, category_id, description, event_date, initiator_id,
    location_id, paid, participant_limit, request_moderation, state,
    created_on, published_on, title
)
SELECT
    'Test annotation ' || n,
    1,
    'Test description ' || n,
    NOW() + (n || ' days')::INTERVAL,
    1,
    1,
    false,
    0,
    true,
    'PUBLISHED',
    NOW(),
    NOW(),
    'Test Event ' || n
FROM generate_series(1, 20) AS n;